### ISSUE TITLE
support yaml config file

### ISSUE THREAD

**Issue by ottijp** [ottijp/az-deployment-denoise#2]
support not only JSON but also yaml.

example:

```
rules:
- providerNamespace: Microsoft.Web
  resourceType: sites
  propertyPath: properties.siteConfig.localMySqlEnabled
- resourceName: testmodified
```

## priority

* If the command is executed with `-f`, read it
* If `./az-deployment-denoise.json` exists, read it
* If `./az-deployment-denoise.yml` exists, read it
